### ISSUE TITLE
Default values analog 9

### ISSUE THREAD

**Issue by MrLegge** [photodude/DualVNH5019MotorShieldMod3#3]
In your library code you reference `_CS4 = 9; //analog 9 pin`    should that read `_CS4 = A9; //analog 9 pin`

**Comment by photodude** [comment]
Thanks @MrLegge I have Fixed that issue in the Repo. If you find any other issues, please let me know and I'll try to include them in the next release.
Also feel free to make the changes and submit them as PR's for consideration.
